[Variables]
Total=7
LastOpen=2

Name1=Vertical list
Cover1=preset_1.png
Dir1=preset_1.inc

Name2=Basic app list
Cover2=preset_2.png
Dir2=preset_2.inc

Name3=Abstract
Cover3=preset_3.png
Dir3=preset_3.inc

Name4=Game ribbon
Cover4=preset_4.png
Dir4=preset_4.inc

Name5=Elegance
Cover5=preset_5.png
Dir5=preset_5.inc

Name6=Roms and emulators
Cover6=preset_6.png
Dir6=preset_6.inc

Name7=Simple TV interface
Cover7=preset_7.png
Dir7=preset_7.inc

Name8=Fixed background
Cover8=preset_8.png
Dir8=preset_8.inc