[Variables]
Layout=horizontal.inc
LoadMeter={'background_meter.inc','icon_meter.inc'}
SkinWidth=0.9
SkinX=0.05
SkinY=0.15
List=list_game.inc
Space=10
RowSpace=0
Rows=1
ScrollSpeed=0.1
ScrollDivider=8
Transition=5
IconSolid=0,0,0,150
IconTint=255,255,255
IconScale=0.5
BannerWidth=384
BannerHeight=756
Update=20
ClickThrough=0
CoverAspectRatio=2
StaticBackground=1
Keyboard=1
Controller=1
LaunchAction=[!CommandMeasure Animation "launch_effect()"]
SoundHover=hover_1.wav
SoundClick=launch.wav
SoundExit=exit.wav


