[Cover1] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(1)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(1)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(1)"]
ImageName=#@#Cover\#Cover1#
Hidden=0

[Cover2] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(2)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(2)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(2)"]
ImageName=#@#Cover\#Cover2#
Hidden=0

[Cover3] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(3)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(3)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(3)"]
ImageName=#@#Cover\#Cover3#
Hidden=0