[Icon1] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(1)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(1)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(1)"]
ImageName=#@#Icons\#Icon1#
Hidden=0

[Icon2] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(2)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(2)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(2)"]
ImageName=#@#Icons\#Icon2#
Hidden=0

[Icon3] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(3)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(3)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(3)"]
ImageName=#@#Icons\#Icon3#
Hidden=0

[Icon4] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(4)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(4)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(4)"]
ImageName=#@#Icons\#Icon4#
Hidden=0

[Icon5] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(5)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(5)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(5)"]
ImageName=#@#Icons\#Icon5#
Hidden=0

[Icon6] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(6)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(6)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(6)"]
ImageName=#@#Icons\#Icon6#
Hidden=0