[Variables]
Total=6
LastOpen=5

Name1=Citra 3DS
Icon1=citra.png
Cover1=
Dir1=E:\roms\3DS\canary-mingw\citra-qt.exe

Name2=PCSX2
Icon2=pcsx2.png
Dir2=E:\roms\pcsx2-v1.5.0-dev-2698-g8ff024921-windows-x86\pcsx2.exe
Cover2=

Name3=RPCS3
Icon3=rpcs3.png
Dir3=E:\roms\rpcs3-v0.0.5-7120-8b693ed7_win64\rpcs3.exe
Cover3=

Name4=Snes9x
Icon4=snes.png
Cover4=
Dir4=E:\roms\SNES\snes9x-x64.exe

Name5=CEMU
Icon5=cemu.png
Cover5=
Dir5=E:\roms\WiiU\Cemu.exe
Name6=Yuzu
Icon6=360px-Yuzu-icon.svg.png
Cover6=
Background6=
Dir6=C:\Users\Finch\AppData\Local\yuzu\canary\yuzu.exe
