[Variables]
Total=4
LastOpen=3


Name1=Sign out
Icon1=sign-out.png
Cover1=sign-out.jpg
Dir1=logoff.exe
Background1=power.jpg

Name2=Restart
Icon2=restart.png
Cover2=restart.jpg
Dir2=[shutdown -r -t 10]
Background2=power.jpg

Name3=Shutdown
Icon3=power.png
Cover3=shutdown.jpg
Dir3=[shutdown.exe -s -t 10]
Background3=power.jpg

Name4=Hibernate
Icon4=sleep.png
Cover4=sleep.jpg
Dir4=[rundll32.exe PowrProf.dll,SetSuspendState 0,1,0]
Background4=power.jpg
