[Variables]
Total=14
LastOpen=3

Name1=Insurgency Sandstorm 
Icon1=IS.png
Cover1=IS.jpg
Dir1=steam://rungameid/581320
Background1=IS.jpg

Name2=Resident Evil 2
Icon2=re2.png
Dir2=D:\Program Files\Resident Evil 2\re2.exe
Cover2=RE2.jpg
Background2=RE2.jpg

Name3=Metro Exodus
Icon3=MetroE.png
Dir3=D:\Program Files\Metro - Exodus\MetroExodus.exe
Cover3=MetroE.jpg
Background3=Metro-Exodus-4K-Wallpaper-1.jpg

Name4=Far Cry New Dawn
Icon4=fcnd.png
Cover4=fcnd.jpg
Dir4=D:\Program Files\Far Cry - New Dawn\bin\FarCryNewDawn.exe
Background4=fcnd.jpg

Name5=Final Fantasy XV
Icon5=ffxv.png
Cover5=ffxv.jpg
Dir5=D:\Program Files\FFXV\ffxv_s.exe
Background5=ffxv.jpg

Name6=Nier Automata
Icon6=nier.png
Cover6=nier.jpg
Dir6=D:\Program Files\NieR - Automata\NieRAutomata.exe
Background6=nier.jpg

Name7=Assassin's Creed Odysseys
Icon7=ACO.png
Cover7=ACO.jpg
Dir7=D:\Program Files\Assassin's Creed - Odyssey\ACOdyssey.exe
Background7=ACO.jpg

Name8=The Witcher 3: Wild Hunt
Icon8=witcher3.png
Cover8=witcher3.jpg
Dir8=D:\Program Files\The Witcher 3 - Wild Hunt\bin\x64\witcher3.exe
Background8=witcher3.jpg

Name9=Warframe
Icon9=warframe.png
Cover9=warframe.jpg
Dir9=C:\Users\Finch\AppData\Local\Warframe\Downloaded\Test\Tools\Launcher.exe
Background9=warframe.jpg

Name10=Batman: Arkham Knight
Icon10=arkhamknight.png
Cover10=arkhamknight.jpg
Dir10=D:\Program Files\Batman - Arkham Knight\Binaries\Win64\BatmanAK.exe
Background10=batman_arkham.jpg

Name11=The Legend of Zelda: Breath of the Wild
Icon11=botw.png
Cover11=botw.jpg
Dir11=E:\roms\WiiU\Cemu.exe" "-g" "E:\roms\WiiU\rom\The Legend of Zelda Breath of the Wild\code\U-King.rpx" "-f
Background11=botw.jpg

Name12=Shadow of the Tomb Raider
Icon12=SOTTR.png
Cover12=SOTTR.jpg
Dir12=D:\Program Files\Shadow of the Tomb Raider\SOTTR.exe
Background12=SOTTR.jpg

Name13=The Sims 4
Icon13=sims4.png
Cover13=sims4.png
Dir13=D:\Program Files\The Sims 4\Game\Bin\TS4_x64.exe
Background13=sims4.jpg

Name14=Minecraft 
Icon14=minecraft.png
Cover14=minecraft.png
Dir14=C:\Users\Finch\AppData\Roaming\.minecraft\MinecraftLauncher.exe
Background14=minecraft.jpg

Name15=Ace Combat 7
Icon15=ac7.png
Cover15=ac7.jpg
Background15=ac7.jpg
Dir15=D:\Program Files\Ace Combat 7 - Skies Unknown\Ace7Game.exe
