[Variables]
Total=3
LastOpen=3

Name1=Metal Slug Anthology
Icon1=
Cover1=metalslug.jpg
Dir1="E:\roms\pcsx2-v1.5.0-dev-2698-g8ff024921-windows-x86\pcsx2.exe" "--fullscreen" "E:\roms\pcsx2-v1.5.0-dev-2698-g8ff024921-windows-x86\Roms\Metal Slug Anthology (USA).iso"

Name2=Scott Pilgrim vs. the World: The Game
Icon2=
Dir2="E:\roms\rpcs3-v0.0.5-7120-8b693ed7_win64\rpcs3.exe" "E:\roms\rpcs3-v0.0.5-7120-8b693ed7_win64\dev_hdd0\game\NPUB30162\USRDIR\EBOOT.BIN"
Cover2=SPvTW.jpg

Name3=Breath of the wild
Icon3=botw.png
Dir3="E:\roms\WiiU\Cemu.exe" "-g" "E:\roms\WiiU\rom\The Legend of Zelda Breath of the Wild\code\U-King.rpx" "-f"
Cover3=botw.jpg
