[Variables]
Total=12
LastOpen=11

Name1=Photos
Icon1=Photo.png
Cover1=Photo.jpg
Dir1=shell:appsFolder\Microsoft.Windows.Photos_8wekyb3d8bbwe!App

Name2=Chrome
Icon2=chrome.png
Dir2=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Cover2=chrome.jpg

Name3=After Effect
Icon3=ae.png
Dir3=C:\Program Files\Adobe\Adobe After Effects CC 2018\Support Files\AfterFX.exe
Cover3=ae.png

Name4=GM:Studio
Icon4=gms.png
Cover4=gms.jpg
Dir4=D:\Program Files\GameMaker-Studio\Startilla_V3.exe

Name5=Photoshop
Icon5=ps.png
Cover5=ps.jpg
Dir5=C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe

Name6=Movies
Icon6=movie.png
Cover6=movie.jpg
Dir6=C:\Program Files\VideoLAN\VLC\vlc.exe

Name7=Unity
Icon7=unity.png
Cover7=unity.jpg
Dir7=D:\Program Files\Editor\Unity.exe

Name8=Discord
Icon8=discord.png
Cover8=discord.jpg
Dir8=C:\Users\siegw\AppData\Local\Discord\Update.exe" "--processStart" "Discord.exe

Name9=Groove Music
Icon9=music.png
Cover9=music.jpg
Dir9=shell:appsFolder\Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic

Name10=My office
Icon10=office.png
Cover10=office.jpg
Dir10=shell:appsFolder\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe!Microsoft.MicrosoftOfficeHub

Name11=This PC
Icon11=PC.png
Cover11=PC.jpg
Dir11=shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}

Name12=Setting
Icon12=setting.png
Cover12=setting.jpg
Dir12=ms-settings:

Name13=new entry
Icon13=new.png
Cover13=
Background13=
Dir13=
