[Variables]
Total=7
LastOpen=6

Name1=Citra 3DS
Icon1=citra.png
Cover1=
Dir1=F:\Emulator\3DS\canary-mingw\citra-qt.exe

Name2=PCSX2
Icon2=pcsx2.png
Dir2=F:\Emulator\pcsx2-v1.5.0-dev-2698-g8ff024921-windows-x86\pcsx2.exe
Cover2=

Name3=RPCS3
Icon3=rpcs3.png
Dir3=F:\Emulator\rpcs3-v0.0.5-7120-8b693ed7_win64\rpcs3.exe
Cover3=

Name4=Snes9x
Icon4=snes.png
Cover4=
Dir4=F:\Emulator\SNES\snes9x-x64.exe

Name5=CEMU
Icon5=cemu.png
Cover5=
Dir5=F:\Emulator\WiiU\Cemu.exe

Name6=Yuzu
Icon6=360px-Yuzu-icon.svg.png
Cover6=
Background6=
Dir6=C:\Users\Finch\AppData\Local\yuzu\canary\yuzu.exe

Name7=DeSmuME
Icon7=25991.png
Cover7=
Background7=
Dir7=F:\Emulator\NDS\DeSmuME_git#42817475_x64.exe
