[Variables]
Total=5
LastOpen=5

Name1=Breath of the wild
Icon1=botw.png
Cover1=botw_wiiu.jpg
Dir1=E:\roms\WiiU\Cemu.exe" "-g" "E:\roms\WiiU\rom\The Legend of Zelda Breath of the Wild\code\U-King.rpx" "-f

Name2=Scott Pilgrim vs. the World: The Game
Icon2=
Dir2="E:\roms\rpcs3-v0.0.5-7120-8b693ed7_win64\rpcs3.exe" "E:\roms\rpcs3-v0.0.5-7120-8b693ed7_win64\dev_hdd0\game\NPUB30162\USRDIR\EBOOT.BIN"
Cover2=SPvTW.jpg

Name3=Metal Slug Anthology
Icon3=
Dir3=E:\roms\pcsx2-v1.5.0-dev-2698-g8ff024921-windows-x86\pcsx2.exe" "--fullscreen" "E:\roms\pcsx2-v1.5.0-dev-2698-g8ff024921-windows-x86\Roms\Metal Slug Anthology (USA).iso
Cover3=metalslug.jpg

Name4=Tomodachi Collection
Icon4=new.png
Cover4=tomodachi.jpg
Background4=
Dir4="E:\roms\NDS\DeSmuME_git#42817475_x64.exe" "E:\roms\NDS\Roms\Tomodachi_Collection_Eng_v0.8.nds"

Name5=Rune Factory 3
Icon5=new.png
Cover5=RF3.jpg
Background5=
Dir5="E:\roms\NDS\DeSmuME_git#42817475_x64.exe" "E:\roms\NDS\Roms\Rune_Factory_3_A_Fantasy_Harvest_Moon_Undub.nds"
Background3=
Background1=
