[Variables]
Total=13
LastOpen=1

Name1=Insurgency Sandstorm 
Icon1=IS.png
Cover1=IS.jpg
Dir1=steam://rungameid/581320
Background1=IS.jpg

Name2=Control
Icon2=control_ico.png
Dir2=D:\Program Files\Control\Control_DX11.exe
Cover2=control_cover.jpg
Background2=control_bkg.jpg

Name3=Resident Evil 2
Icon3=re2.png
Dir3=D:\Program Files\Resident Evil 2\re2.exe
Cover3=re2.jpg
Background3=RE2.jpg

Name4=Warframe
Icon4=warframe.png
Cover4=warframe.jpg
Dir4=steam://rungameid/230410
Background4=warframe.jpg

Name5=Metro Exodus
Icon5=MetroE.png
Cover5=MetroE.jpg
Dir5=D:\Program Files\Metro - Exodus\MetroExodus.exe
Background5=Metro-Exodus-4K-Wallpaper-1.jpg

Name6=Ghost Recon Wildlands
Icon6=GRWI
Cover6=GRWC.jpg
Dir6=steam://rungameid/460930
Background6=GRWB.jpg

Name7=Assassin's Creed Origins
Icon7=ACOrigin_ico.png
Cover7=ACOrigin_cover.jpg
Dir7=D:\Program Files\Assassin's Creed - Origins\ACOrigins.exe
Background7=ACOrigin_bkg.jpg

Name8=Assassin's Creed Oddysey
Icon8=ACO.png
Cover8=ACO.jpg
Dir8=D:\Program Files\Assassin's Creed - Odyssey\ACOdyssey.exe
Background8=ACO.jpg

Name9=Batman: Arkham Knight
Icon9=arkhamknight.png
Cover9=arkhamknight.jpg
Dir9=D:\Program Files\Batman - Arkham Knight\Binaries\Win64\BatmanAK.exe
Background9=batman_arkham.jpg

Name10=Nier Automata
Icon10=nier.png
Cover10=nier.jpg
Dir10=D:\Program Files\NieR - Automata\NieRAutomata.exe
Background10=nier.jpg


Name11=The Witcher 3: Wild Hunt
Icon11=witcher3.png
Cover11=witcher3.jpg
Background11=witcher3.jpg
Dir11=D:\Program Files\The Witcher 3 - Wild Hunt\bin\x64\witcher3.exe


Name12=Far cry 5
Icon12=FC5.png
Cover12=13607.jpg
Dir12=steam://rungameid/552520
Background12=FC5.jpg

Name13=Minecraft
Icon13=minecraft.png
Cover13=minecraft.png
Background13=minecraft.jpg
Dir13=C:\Users\Finch\AppData\Roaming\.minecraft\MinecraftLauncher.exe
