[Variables]
Total=15
LastOpen=4

Name1=This PC
Icon1=PC.png
Cover1=PC.jpg
Dir1=shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}

Name2=Firefox
Icon2=firefox.png
Dir2=C:\Program Files\Mozilla Firefox\firefox.exe
Cover2=firefox.jpg

Name3=Steam Big Picture
Icon3=steam.png
Dir3="C:\Program Files (x86)\Steam\Steam.exe" "-bigpicture"
Cover3=steam.jpg

Name4=Flashpoint
Icon4=flashpoint.png
Cover4=flashpoint.jpg
Dir4=F:\Emulator\Flashpoint\Start Flashpoint.lnk

Name5=Popcorn time
Icon5=popcorntime.png
Cover5=popcorntime.png
Dir5=C:\Program Files (x86)\Popcorn Time\PopcornTimeDesktop.exe

Name6=Chrome
Icon6=chrome.png
Cover6=chrome.jpg
Dir6=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

Name7=After Effect
Icon7=ae.png
Cover7=ae.png
Dir7=F:\Program Files\Adobe After Effects CC 2015\Support Files\AfterFX.exe

Name8=Photoshop
Icon8=ps.png
Cover8=ps.jpg
Dir8=F:\Program Files\Adobe Photoshop CC 2015\Photoshop.exe

Name9=Discord
Icon9=discord.png
Cover9=discord.jpg
Dir9=C:\Users\siegw\AppData\Local\Discord\Update.exe" "--processStart" "Discord.exe

Name10=BOTW editor
Icon10=botw.png
Cover10=botw.jpg
Dir10=F:\Emulator\WiiU\rom\The Legend of Zelda Breath of the Wild\botw_editor.exe

Name11=GM:Studio
Icon11=gms.png
Cover11=gms.jpg
Dir11=steam://rungameid/585410

Name12=Unity
Icon12=unity.png
Cover12=unity.jpg
Dir12=D:\Program Files\Editor\Unity.exe

Name13=Photos
Icon13=Photo.png
Cover13=Photo.jpg
Background13=
Dir13=shell:appsFolder\Microsoft.Windows.Photos_8wekyb3d8bbwe!App


Name15=Setting
Icon15=setting.png
Cover15=setting.jpg
Background15=
Dir15=ms-settings:

Background1=
Background11=
Background12=
Background10=
Background9=
Background7=
Background6=
Background5=
Background4=
Background3=
Background2=
Background8=
Name14=My office
Icon14=office.png
Cover14=office.jpg
Background14=
Dir14=shell:appsFolder\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe!Microsoft.MicrosoftOfficeHub
