[Variables]
Total=14
LastOpen=11

Name1=Ghost recon: Wildlands 
Icon1=wildlands.png
Cover1=wildlands.jpg
Dir1=steam://rungameid/460930
Background1=wildlands.jpg

Name2=Insurgency Sandstorm
Icon2=IS.png
Dir2=steam://rungameid/581320
Cover2=IS.jpg
Background2=IS.jpg

Name3=Resident Evil 2
Icon3=re2.png
Dir3=D:\Program Files\Resident Evil 2\re2.exe
Cover3=RE2.jpg
Background3=RE2.jpg

Name4=Final Fantasy XV
Icon4=ffxv.png
Cover4=ffxv.jpg
Dir4=D:\Program Files\FFXV\ffxv_s.exe
Background4=ffxv.jpg

Name5=Nier Automata
Icon5=nier.png
Cover5=nier.jpg
Dir5=D:\Program Files\NieR - Automata\NieRAutomata.exe
Background5=nier.jpg

Name6=The Witcher 3: Wild Hunt
Icon6=witcher3.png
Cover6=witcher3.jpg
Dir6=D:\Program Files\The Witcher 3 - Wild Hunt\bin\x64\witcher3.exe
Background6=witcher3.jpg

Name7=Assassin's Creed Odysseys
Icon7=ACO.png
Cover7=ACO.jpg
Dir7=D:\Program Files\Assassin's Creed - Odyssey\ACOdyssey.exe
Background7=ACO.jpg

Name8=Warframe
Icon8=warframe.png
Cover8=warframe.jpg
Dir8=C:\Users\Finch\AppData\Local\Warframe\Downloaded\Test\Tools\Launcher.exe
Background8=warframe.jpg

Name9=Battlefield 4
Icon9=bf4.png
Cover9=bf4.jpg
Dir9=D:\Program Files\Battlefield 4\bf4.exe
Background9=bf4.jpg

Name10=Shadow of the Tomb Raider
Icon10=SOTTR.png
Cover10=SOTTR.jpg
Dir10=D:\Program Files\Shadow of the Tomb Raider\SOTTR.exe
Background10=SOTTR.jpg

Name11=The Sims 4
Icon11=sims4.png
Cover11=sims4.png
Dir11=D:\Program Files\The Sims 4\Game\Bin\TS4_x64.exe
Background11=sims4.jpg

Name12=Minecraft
Icon12=minecraft.png
Cover12=minecraft.png
Dir12=C:\Users\Finch\AppData\Roaming\.minecraft\MinecraftLauncher.exe
Background12=minecraft.jpg

Name13=Batman: Arkham Knight
Icon13=arkhamknight.png
Cover13=arkhamknight.jpg
Dir13=D:\Program Files\Batman - Arkham Knight\Binaries\Win64\BatmanAK.exe
Background13=batman_arkham.jpg

Name14=The Legend of Zelda: Breath of the Wild 
Icon14=botw.png
Cover14=botw.jpg
Dir14="E:\roms\WiiU\Cemu.exe" "-g" "E:\roms\WiiU\rom\The Legend of Zelda Breath of the Wild\code\U-King.rpx" "-f"
Background14=botw.jpg
