[Cover1] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(1)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(1)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(1)"]
ImageName=#@#Cover\#Cover1#
Hidden=0

[Cover2] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(2)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(2)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(2)"]
ImageName=#@#Cover\#Cover2#
Hidden=0

[Cover3] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(3)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(3)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(3)"]
ImageName=#@#Cover\#Cover3#
Hidden=0

[Cover4] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(4)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(4)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(4)"]
ImageName=#@#Cover\#Cover4#
Hidden=0

[Cover5] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(5)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(5)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(5)"]
ImageName=#@#Cover\#Cover5#
Hidden=0

[Cover6] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(6)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(6)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(6)"]
ImageName=#@#Cover\#Cover6#
Hidden=0

[Cover7] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(7)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(7)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(7)"]
ImageName=#@#Cover\#Cover7#
Hidden=0

[Directory1] 
Meter=String 
MeterStyle=Directory
Text=#Dir1# 
Hidden=0

[Directory2] 
Meter=String 
MeterStyle=Directory
Text=#Dir2# 
Hidden=0

[Directory3] 
Meter=String 
MeterStyle=Directory
Text=#Dir3# 
Hidden=0

[Directory4] 
Meter=String 
MeterStyle=Directory
Text=#Dir4# 
Hidden=0

[Directory5] 
Meter=String 
MeterStyle=Directory
Text=#Dir5# 
Hidden=0

[Directory6] 
Meter=String 
MeterStyle=Directory
Text=#Dir6# 
Hidden=0

[Directory7] 
Meter=String 
MeterStyle=Directory
Text=#Dir7# 
Hidden=0

[Title1] 
Meter=String 
MeterStyle=Title 
Text=#Name1# 
Hidden=0

[Title2] 
Meter=String 
MeterStyle=Title 
Text=#Name2# 
Hidden=0

[Title3] 
Meter=String 
MeterStyle=Title 
Text=#Name3# 
Hidden=0

[Title4] 
Meter=String 
MeterStyle=Title 
Text=#Name4# 
Hidden=0

[Title5] 
Meter=String 
MeterStyle=Title 
Text=#Name5# 
Hidden=0

[Title6] 
Meter=String 
MeterStyle=Title 
Text=#Name6# 
Hidden=0

[Title7] 
Meter=String 
MeterStyle=Title 
Text=#Name7# 
Hidden=0