[Icon1] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(1)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(1)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(1)"]
ImageName=#@#Icons\#Icon1#
Hidden=0

[Icon2] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(2)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(2)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(2)"]
ImageName=#@#Icons\#Icon2#
Hidden=0

[Icon3] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(3)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(3)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(3)"]
ImageName=#@#Icons\#Icon3#
Hidden=0

[Icon4] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(4)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(4)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(4)"]
ImageName=#@#Icons\#Icon4#
Hidden=0

[Icon5] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(5)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(5)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(5)"]
ImageName=#@#Icons\#Icon5#
Hidden=0

[Icon6] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(6)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(6)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(6)"]
ImageName=#@#Icons\#Icon6#
Hidden=0

[Icon7] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(7)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(7)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(7)"]
ImageName=#@#Icons\#Icon7#
Hidden=0

[Icon8] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(8)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(8)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(8)"]
ImageName=#@#Icons\#Icon8#
Hidden=0

[Icon9] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(9)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(9)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(9)"]
ImageName=#@#Icons\#Icon9#
Hidden=0

[Icon10] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(10)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(10)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(10)"]
ImageName=#@#Icons\#Icon10#
Hidden=0

[Icon11] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(11)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(11)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(11)"]
ImageName=#@#Icons\#Icon11#
Hidden=0

[Icon12] 
Meter=Image 
MeterStyle=Icon
MouseOverAction=[!CommandMeasure Animation "highlight(12)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(12)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(12)"]
ImageName=#@#Icons\#Icon12#
Hidden=0

[Title1] 
Meter=String 
MeterStyle=Title 
Text=#Name1# 
Hidden=0

[Title2] 
Meter=String 
MeterStyle=Title 
Text=#Name2# 
Hidden=0

[Title3] 
Meter=String 
MeterStyle=Title 
Text=#Name3# 
Hidden=0

[Title4] 
Meter=String 
MeterStyle=Title 
Text=#Name4# 
Hidden=0

[Title5] 
Meter=String 
MeterStyle=Title 
Text=#Name5# 
Hidden=0

[Title6] 
Meter=String 
MeterStyle=Title 
Text=#Name6# 
Hidden=0

[Title7] 
Meter=String 
MeterStyle=Title 
Text=#Name7# 
Hidden=0

[Title8] 
Meter=String 
MeterStyle=Title 
Text=#Name8# 
Hidden=0

[Title9] 
Meter=String 
MeterStyle=Title 
Text=#Name9# 
Hidden=0

[Title10] 
Meter=String 
MeterStyle=Title 
Text=#Name10# 
Hidden=0

[Title11] 
Meter=String 
MeterStyle=Title 
Text=#Name11# 
Hidden=0

[Title12] 
Meter=String 
MeterStyle=Title 
Text=#Name12# 
Hidden=0

[Background1] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background1#
Hidden=0

[Background2] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background2#
Hidden=0

[Background3] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background3#
Hidden=0

[Background4] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background4#
Hidden=0

[Background5] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background5#
Hidden=0

[Background6] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background6#
Hidden=0

[Background7] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background7#
Hidden=0

[Background8] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background8#
Hidden=0

[Background9] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background9#
Hidden=0

[Background10] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background10#
Hidden=0

[Background11] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background11#
Hidden=0

[Background12] 
Meter=Image 
MeterStyle=Background
ImageName=#@#Background\#Background12#
Hidden=0

[Cover1] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(1)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(1)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(1)"]
ImageName=#@#Cover\#Cover1#
Hidden=0

[Cover2] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(2)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(2)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(2)"]
ImageName=#@#Cover\#Cover2#
Hidden=0

[Cover3] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(3)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(3)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(3)"]
ImageName=#@#Cover\#Cover3#
Hidden=0

[Cover4] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(4)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(4)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(4)"]
ImageName=#@#Cover\#Cover4#
Hidden=0

[Cover5] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(5)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(5)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(5)"]
ImageName=#@#Cover\#Cover5#
Hidden=0

[Cover6] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(6)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(6)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(6)"]
ImageName=#@#Cover\#Cover6#
Hidden=0

[Cover7] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(7)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(7)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(7)"]
ImageName=#@#Cover\#Cover7#
Hidden=0

[Cover8] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(8)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(8)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(8)"]
ImageName=#@#Cover\#Cover8#
Hidden=0

[Cover9] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(9)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(9)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(9)"]
ImageName=#@#Cover\#Cover9#
Hidden=0

[Cover10] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(10)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(10)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(10)"]
ImageName=#@#Cover\#Cover10#
Hidden=0

[Cover11] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(11)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(11)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(11)"]
ImageName=#@#Cover\#Cover11#
Hidden=0

[Cover12] 
Meter=Image 
MeterStyle=Cover
MouseOverAction=[!CommandMeasure Animation "highlight(12)"]
MouseLeaveAction=[!CommandMeasure Animation "dehighlight(12)"]
LeftMouseUpAction=[!CommandMeasure Animation "interact(12)"]
ImageName=#@#Cover\#Cover12#
Hidden=0

[Directory1] 
Meter=String 
MeterStyle=Directory
Text=#Dir1# 
Hidden=0

[Directory2] 
Meter=String 
MeterStyle=Directory
Text=#Dir2# 
Hidden=0

[Directory3] 
Meter=String 
MeterStyle=Directory
Text=#Dir3# 
Hidden=0

[Directory4] 
Meter=String 
MeterStyle=Directory
Text=#Dir4# 
Hidden=0

[Directory5] 
Meter=String 
MeterStyle=Directory
Text=#Dir5# 
Hidden=0

[Directory6] 
Meter=String 
MeterStyle=Directory
Text=#Dir6# 
Hidden=0

[Directory7] 
Meter=String 
MeterStyle=Directory
Text=#Dir7# 
Hidden=0

[Directory8] 
Meter=String 
MeterStyle=Directory
Text=#Dir8# 
Hidden=0

[Directory9] 
Meter=String 
MeterStyle=Directory
Text=#Dir9# 
Hidden=0

[Directory10] 
Meter=String 
MeterStyle=Directory
Text=#Dir10# 
Hidden=0

[Directory11] 
Meter=String 
MeterStyle=Directory
Text=#Dir11# 
Hidden=0

[Directory12] 
Meter=String 
MeterStyle=Directory
Text=#Dir12# 
Hidden=0